title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          payoff:
            extends: fields/payoff
          mission:
            extends: fields/mission
          text:
            label: Contenuto
            type: blocks
            fieldsets:
              - titlepage
              - paragraph
              - divider
              - contact-form
              - heading
              - text
              - list
              - quote
              - line
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

